<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container32dfunn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container32dfunn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container32dfunn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container32dfunn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container32dfunn\App_KernelDevDebugContainer([
    'container.build_hash' => '32dfunn',
    'container.build_id' => '20e4f109',
    'container.build_time' => 1762458902,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container32dfunn');
